version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: whatsapp_inbox_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whatsapp_inbox
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
